#!/bin/bash

##sampleID is the fastq file folder. 
while read sampleID BASE runID; do 
## upload the data from s3 and unzip
aws s3 cp s3://tgp-upload/${sampleID}/${BASE}_R1.fastq.gz/
aws s3 cp s3://tgp-upload/${sampleID}/${BASE}_R2.fastq.gz/

##star align and generate the transcriptome bam file for salmon
STAR --runThreadN 8  --genomeDir ./ --readFilesIn ${BASE}_R1.fastq.gz ${BASE}_R2.fastq.gz --quantMode TranscriptomeSAM GeneCounts --readFilesCommand zcat 

mv Aligned.toTranscriptome.out.bam ${BASE}.Transcriptome.out.bam 
rm *sam
## ref will be the fasta file, generated by the GFF. 
salmon quant -t homo_index.fa -l A -a ${BASE}.Transcriptome.out.bam -o ${BASE}_quant 

aws s3 cp ${BASE}.Transcriptome.out.bam s3://tgp-sample-processing/${runID}/
aws s3 cp ${BASE}_quant s3://tgp-sample-processing/${runID}/${BASE}_quant/ --recursive
rm *fastq.gz
done < metastoreResponse.txt 
